kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: pd-notify
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 30m
  
    receivers:
    - name: pd-notify
      pagerduty_configs:
      - service_key: {{pager_duty_key}}