apiVersion: v1
kind: Service
metadata:
  name: devicedatastorage
  namespace: default
  labels: 
     app: nuviot
     tier: serviceproviders
spec:
  ports: 
    - port: 80      
  selector:
     app: nuviot
     tier: serviceproviders
     service: devicedatastorage
