apiVersion: apps/v1
kind: Deployment
metadata:
  name: devicedatastorage-deployment
  namespace: default
  labels: 
     app: nuviot
     tier: serviceproviders
spec:
  replicas: 1     
  selector:
    matchLabels:
      app: nuviot
      tier: serviceproviders
  template:
    metadata:
      labels:
        app: nuviot
        tier: serviceproviders
        service: devicedatastorage
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path:   /metrics
        prometheus.io/port:   '80'        
    
    spec:
      containers:
      - name: devicedatastorage
        image: nuviot/devicedatastorage:v1.6.599.1646
        env:
          - name: AccessKey
            valueFrom: 
              secretKeyRef:
                name: instance-secrets
                key: AccessKey
        envFrom:
          - configMapRef:
              name: instance-settings
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: docker-repo-secret       
