apiVersion: apps/v1
kind: Deployment
metadata:
  name: instance-controller-deployment
  namespace: default
  labels: 
     app: nuviot
     tier: front-end
spec:
  replicas: 1     
  selector:
    matchLabels:
      app: nuviot
      tier: front-end
  template:
    metadata:
      labels:
        app: nuviot
        tier: front-end
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path:   /metrics
        prometheus.io/port:   '80'        
    
    spec:
      containers:
      - name: instance-controller
        image: nuviot/instance-controller:v1.6.594.1707
        env:
          - name: AccessKey
            valueFrom: 
              secretKeyRef:
                name: instance-secrets
                key: AccessKey
        envFrom:
          - configMapRef:
              name: instance-settings
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: docker-repo-secret       
