apiVersion: apps/v1
kind: Deployment
metadata:
  name: pem-device-workflow-deployment
  namespace: default
  labels: 
     app: nuviot
     tier: pem-modules
spec:
  replicas: 1     
  selector:
    matchLabels:
      app: nuviot
      tier: pem-modules
  template:
    metadata:
      labels:
        app: nuviot
        tier: pem-modules
        module: pem-device-workflow
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path:   /metrics
        prometheus.io/port:   '80'        
    
    spec:
      containers:
      - name: pem-device-workflow
        image: nuviot/pem-device-workflow:v1.6.598.1721
        env:
          - name: AccessKey
            valueFrom: 
              secretKeyRef:
                name: instance-secrets
                key: AccessKey
        envFrom:
          - configMapRef:
              name: instance-settings      
      imagePullSecrets:
      - name: docker-repo-secret       
