apiVersion: apps/v1
kind: Deployment
metadata:
  name: pem-output-translator-deployment
  namespace: default
  labels: 
     app: nuviot
     tier: pem-modules
spec:
  replicas: 1     
  selector:
    matchLabels:
      app: nuviot
      tier: pem-modules
  template:
    metadata:
      labels:
        app: nuviot
        tier: pem-modules
        module: pem-output-translator
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path:   /metrics
        prometheus.io/port:   '80'        
    
    spec:
      containers:
      - name: pem-output-translator
        image: nuviot/pem-output-translator:v1.6.599.1147
        env:
          - name: AccessKey
            valueFrom: 
              secretKeyRef:
                name: instance-secrets
                key: AccessKey
        envFrom:
          - configMapRef:
              name: instance-settings        
      imagePullSecrets:
      - name: docker-repo-secret       
