apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: 2018-12-19T10:03:00Z
  name: settings-service-deployment
  namespace: default
  labels: 
     app: nuviot
     tier: serviceproviders
spec:
  replicas: 1     
  selector:
    matchLabels:
      app: nuviot
      tier: serviceproviders
  template:
    metadata:
      labels:
        app: nuviot
        tier: serviceproviders
        service: settings
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path:   /metrics
        prometheus.io/port:   '80'                  
    spec:
      containers:
      - name: settings-service
        image: nuviot/settings-service:v1.6.598.1551
        env:
          - name: AccessKey
            valueFrom: 
              secretKeyRef:
                name: instance-secrets
                key: AccessKey
        envFrom:
          - configMapRef:
              name: instance-settings
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: docker-repo-secret     
