apiVersion: v1
kind: Service
metadata:
  name: usagewriter
  namespace: default
  labels: 
     app: nuviot
     teir: serviceproviders
spec:
  ports: 
    - port: 80      
  selector:
     app: nuviot
     teir: serviceproviders
     service: usagewriter
